# Build stage
FROM node:16-alpine AS build
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build api

# Application stage
FROM node:16-alpine

LABEL MAINTAINER="iverly <contact@iverly.net>"
LABEL APP="polycode-api"

WORKDIR /usr/app

COPY package*.json ./
COPY --from=build /usr/src/app/node_modules node_modules
COPY --from=build /usr/src/app/dist dist

EXPOSE 3000
CMD ["node", "dist/apps/api/main.js"]
