name: CI

on:
  push:
    branches:
      - main

jobs:
  build-api-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.x'
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11
      - id: version
        run: echo "::set-output name=version::${{ steps.gitversion.outputs.majorMinorPatch }}-${{ steps.gitversion.outputs.preReleaseTag }}-${{ steps.gitversion.outputs.shortSha }}"
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          dockerfile: Dockerfile.api
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: api
          tags: ${{ steps.version.outputs.version }}
  build-runner-service-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.x'
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11
      - id: version
        run: echo "::set-output name=version::${{ steps.gitversion.outputs.majorMinorPatch }}-${{ steps.gitversion.outputs.preReleaseTag }}-${{ steps.gitversion.outputs.shortSha }}"
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          dockerfile: Dockerfile.runner-service
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: runner-service
          tags: ${{ steps.version.outputs.version }}
  build-java-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.x'
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11
      - id: version
        run: echo "::set-output name=version::${{ steps.gitversion.outputs.majorMinorPatch }}-${{ steps.gitversion.outputs.preReleaseTag }}-${{ steps.gitversion.outputs.shortSha }}"
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: images/java-runner
          dockerfile: images/java-runner/Dockerfile
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: java-runner
          tags: ${{ steps.version.outputs.version }}
  build-javascript-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.x'
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11
      - id: version
        run: echo "::set-output name=version::${{ steps.gitversion.outputs.majorMinorPatch }}-${{ steps.gitversion.outputs.preReleaseTag }}-${{ steps.gitversion.outputs.shortSha }}"
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: images/javascript-runner
          dockerfile: images/javascript-runner/Dockerfile
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: javascript-runner
          tags: ${{ steps.version.outputs.version }}
  build-python-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.x'
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11
      - id: version
        run: echo "::set-output name=version::${{ steps.gitversion.outputs.majorMinorPatch }}-${{ steps.gitversion.outputs.preReleaseTag }}-${{ steps.gitversion.outputs.shortSha }}"
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: images/python-runner
          dockerfile: images/python-runner/Dockerfile
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: python-runner
          tags: ${{ steps.version.outputs.version }}
  build-rust-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.x'
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11
      - id: version
        run: echo "::set-output name=version::${{ steps.gitversion.outputs.majorMinorPatch }}-${{ steps.gitversion.outputs.preReleaseTag }}-${{ steps.gitversion.outputs.shortSha }}"
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: images/rust-runner
          dockerfile: images/rust-runner/Dockerfile
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: rust-runner
          tags: ${{ steps.version.outputs.version }}
